// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vimonade.proto

package vimonade

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CopyRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyRequest) Reset()         { *m = CopyRequest{} }
func (m *CopyRequest) String() string { return proto.CompactTextString(m) }
func (*CopyRequest) ProtoMessage()    {}
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d1d9016bdda1f4a, []int{0}
}

func (m *CopyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyRequest.Unmarshal(m, b)
}
func (m *CopyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyRequest.Marshal(b, m, deterministic)
}
func (m *CopyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyRequest.Merge(m, src)
}
func (m *CopyRequest) XXX_Size() int {
	return xxx_messageInfo_CopyRequest.Size(m)
}
func (m *CopyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyRequest proto.InternalMessageInfo

func (m *CopyRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CopyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyResponse) Reset()         { *m = CopyResponse{} }
func (m *CopyResponse) String() string { return proto.CompactTextString(m) }
func (*CopyResponse) ProtoMessage()    {}
func (*CopyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d1d9016bdda1f4a, []int{1}
}

func (m *CopyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyResponse.Unmarshal(m, b)
}
func (m *CopyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyResponse.Marshal(b, m, deterministic)
}
func (m *CopyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyResponse.Merge(m, src)
}
func (m *CopyResponse) XXX_Size() int {
	return xxx_messageInfo_CopyResponse.Size(m)
}
func (m *CopyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CopyResponse proto.InternalMessageInfo

type PasteRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasteRequest) Reset()         { *m = PasteRequest{} }
func (m *PasteRequest) String() string { return proto.CompactTextString(m) }
func (*PasteRequest) ProtoMessage()    {}
func (*PasteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d1d9016bdda1f4a, []int{2}
}

func (m *PasteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasteRequest.Unmarshal(m, b)
}
func (m *PasteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasteRequest.Marshal(b, m, deterministic)
}
func (m *PasteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasteRequest.Merge(m, src)
}
func (m *PasteRequest) XXX_Size() int {
	return xxx_messageInfo_PasteRequest.Size(m)
}
func (m *PasteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PasteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PasteRequest proto.InternalMessageInfo

func (m *PasteRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PasteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasteResponse) Reset()         { *m = PasteResponse{} }
func (m *PasteResponse) String() string { return proto.CompactTextString(m) }
func (*PasteResponse) ProtoMessage()    {}
func (*PasteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d1d9016bdda1f4a, []int{3}
}

func (m *PasteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasteResponse.Unmarshal(m, b)
}
func (m *PasteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasteResponse.Marshal(b, m, deterministic)
}
func (m *PasteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasteResponse.Merge(m, src)
}
func (m *PasteResponse) XXX_Size() int {
	return xxx_messageInfo_PasteResponse.Size(m)
}
func (m *PasteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PasteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PasteResponse proto.InternalMessageInfo

type SendFileRequest struct {
	// Types that are valid to be assigned to Data:
	//	*SendFileRequest_Info
	//	*SendFileRequest_ChunkData
	Data                 isSendFileRequest_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SendFileRequest) Reset()         { *m = SendFileRequest{} }
func (m *SendFileRequest) String() string { return proto.CompactTextString(m) }
func (*SendFileRequest) ProtoMessage()    {}
func (*SendFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d1d9016bdda1f4a, []int{4}
}

func (m *SendFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendFileRequest.Unmarshal(m, b)
}
func (m *SendFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendFileRequest.Marshal(b, m, deterministic)
}
func (m *SendFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendFileRequest.Merge(m, src)
}
func (m *SendFileRequest) XXX_Size() int {
	return xxx_messageInfo_SendFileRequest.Size(m)
}
func (m *SendFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendFileRequest proto.InternalMessageInfo

type isSendFileRequest_Data interface {
	isSendFileRequest_Data()
}

type SendFileRequest_Info struct {
	Info *FileInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type SendFileRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*SendFileRequest_Info) isSendFileRequest_Data() {}

func (*SendFileRequest_ChunkData) isSendFileRequest_Data() {}

func (m *SendFileRequest) GetData() isSendFileRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SendFileRequest) GetInfo() *FileInfo {
	if x, ok := m.GetData().(*SendFileRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (m *SendFileRequest) GetChunkData() []byte {
	if x, ok := m.GetData().(*SendFileRequest_ChunkData); ok {
		return x.ChunkData
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SendFileRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SendFileRequest_Info)(nil),
		(*SendFileRequest_ChunkData)(nil),
	}
}

type SendFileResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendFileResponse) Reset()         { *m = SendFileResponse{} }
func (m *SendFileResponse) String() string { return proto.CompactTextString(m) }
func (*SendFileResponse) ProtoMessage()    {}
func (*SendFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d1d9016bdda1f4a, []int{5}
}

func (m *SendFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendFileResponse.Unmarshal(m, b)
}
func (m *SendFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendFileResponse.Marshal(b, m, deterministic)
}
func (m *SendFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendFileResponse.Merge(m, src)
}
func (m *SendFileResponse) XXX_Size() int {
	return xxx_messageInfo_SendFileResponse.Size(m)
}
func (m *SendFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendFileResponse proto.InternalMessageInfo

func (m *SendFileResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SendFileResponse) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type FileInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FileType             string   `protobuf:"bytes,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d1d9016bdda1f4a, []int{6}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileInfo) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func init() {
	proto.RegisterType((*CopyRequest)(nil), "vimonade.CopyRequest")
	proto.RegisterType((*CopyResponse)(nil), "vimonade.CopyResponse")
	proto.RegisterType((*PasteRequest)(nil), "vimonade.PasteRequest")
	proto.RegisterType((*PasteResponse)(nil), "vimonade.PasteResponse")
	proto.RegisterType((*SendFileRequest)(nil), "vimonade.SendFileRequest")
	proto.RegisterType((*SendFileResponse)(nil), "vimonade.SendFileResponse")
	proto.RegisterType((*FileInfo)(nil), "vimonade.FileInfo")
}

func init() {
	proto.RegisterFile("vimonade.proto", fileDescriptor_4d1d9016bdda1f4a)
}

var fileDescriptor_4d1d9016bdda1f4a = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcb, 0x4f, 0xc2, 0x40,
	0x10, 0xc6, 0xa9, 0x29, 0x84, 0x0e, 0x2f, 0xb3, 0xf1, 0x81, 0xf5, 0x20, 0xa9, 0x1e, 0x7a, 0xe2,
	0x80, 0x07, 0x13, 0x3c, 0xf9, 0x88, 0xc1, 0x9b, 0x59, 0x8c, 0x57, 0xb2, 0xd2, 0x21, 0x6e, 0x84,
	0xdd, 0x4a, 0xb7, 0x4d, 0xea, 0x7f, 0xe8, 0x7f, 0x65, 0x76, 0xfb, 0x0c, 0x12, 0x6f, 0x3b, 0xdf,
	0x7c, 0xdf, 0xcc, 0xf4, 0x97, 0x42, 0x3f, 0xe1, 0x1b, 0x29, 0x58, 0x80, 0xe3, 0x70, 0x2b, 0x95,
	0x24, 0xed, 0xa2, 0xf6, 0x2e, 0xa1, 0xf3, 0x20, 0xc3, 0x94, 0xe2, 0x57, 0x8c, 0x91, 0x22, 0x47,
	0xd0, 0x4c, 0xd8, 0x3a, 0xc6, 0xa1, 0x35, 0xb2, 0x7c, 0x87, 0x66, 0x85, 0xd7, 0x87, 0x6e, 0x66,
	0x8a, 0x42, 0x29, 0x22, 0xf4, 0xae, 0xa0, 0xfb, 0xc2, 0x22, 0x85, 0xff, 0xa7, 0x06, 0xd0, 0xcb,
	0x5d, 0x79, 0x2c, 0x80, 0xc1, 0x1c, 0x45, 0xf0, 0xc4, 0xd7, 0x65, 0xd2, 0x07, 0x9b, 0x8b, 0x95,
	0x34, 0xc1, 0xce, 0x84, 0x8c, 0xcb, 0x3b, 0xb5, 0xe9, 0x59, 0xac, 0xe4, 0xac, 0x41, 0x8d, 0x83,
	0x5c, 0x00, 0x2c, 0x3f, 0x62, 0xf1, 0xb9, 0x08, 0x98, 0x62, 0xc3, 0x83, 0x91, 0xe5, 0x77, 0x67,
	0x0d, 0xea, 0x18, 0xed, 0x91, 0x29, 0x76, 0xdf, 0x02, 0x5b, 0xb7, 0xbc, 0x29, 0x1c, 0x56, 0x5b,
	0xb2, 0xcd, 0x84, 0x80, 0x2d, 0xd8, 0xa6, 0xb8, 0xcf, 0xbc, 0xb5, 0x16, 0xf1, 0x6f, 0x34, 0xa3,
	0x7a, 0xd4, 0xbc, 0xbd, 0x5b, 0x68, 0x17, 0x8b, 0xf7, 0x66, 0xce, 0xc1, 0x59, 0xf1, 0x35, 0x2e,
	0x54, 0x1a, 0x66, 0x41, 0x87, 0xb6, 0xb5, 0xf0, 0x9a, 0x86, 0x38, 0xf9, 0xb1, 0x60, 0xf0, 0x96,
	0xdf, 0x3f, 0xc7, 0x6d, 0xc2, 0x97, 0x48, 0x6e, 0xc0, 0xd6, 0xe4, 0xc8, 0x71, 0xf5, 0x65, 0x35,
	0xdc, 0xee, 0xc9, 0xae, 0x9c, 0x93, 0x6a, 0x90, 0x29, 0x34, 0x0d, 0x3c, 0x52, 0xb3, 0xd4, 0x99,
	0xbb, 0xa7, 0x7f, 0xf4, 0x32, 0x7b, 0x07, 0xb6, 0x26, 0x40, 0xce, 0x2a, 0xcb, 0x0e, 0x77, 0xd7,
	0xdd, 0xd7, 0x2a, 0x06, 0xf8, 0xd6, 0x7b, 0xcb, 0xfc, 0x27, 0xd7, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x8a, 0xa2, 0x5c, 0xa7, 0x39, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VimonadeServiceClient is the client API for VimonadeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VimonadeServiceClient interface {
	Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error)
	Paste(ctx context.Context, in *PasteRequest, opts ...grpc.CallOption) (*PasteResponse, error)
	Send(ctx context.Context, opts ...grpc.CallOption) (VimonadeService_SendClient, error)
}

type vimonadeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVimonadeServiceClient(cc grpc.ClientConnInterface) VimonadeServiceClient {
	return &vimonadeServiceClient{cc}
}

func (c *vimonadeServiceClient) Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error) {
	out := new(CopyResponse)
	err := c.cc.Invoke(ctx, "/vimonade.VimonadeService/Copy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vimonadeServiceClient) Paste(ctx context.Context, in *PasteRequest, opts ...grpc.CallOption) (*PasteResponse, error) {
	out := new(PasteResponse)
	err := c.cc.Invoke(ctx, "/vimonade.VimonadeService/Paste", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vimonadeServiceClient) Send(ctx context.Context, opts ...grpc.CallOption) (VimonadeService_SendClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VimonadeService_serviceDesc.Streams[0], "/vimonade.VimonadeService/Send", opts...)
	if err != nil {
		return nil, err
	}
	x := &vimonadeServiceSendClient{stream}
	return x, nil
}

type VimonadeService_SendClient interface {
	Send(*SendFileRequest) error
	CloseAndRecv() (*SendFileResponse, error)
	grpc.ClientStream
}

type vimonadeServiceSendClient struct {
	grpc.ClientStream
}

func (x *vimonadeServiceSendClient) Send(m *SendFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *vimonadeServiceSendClient) CloseAndRecv() (*SendFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VimonadeServiceServer is the server API for VimonadeService service.
type VimonadeServiceServer interface {
	Copy(context.Context, *CopyRequest) (*CopyResponse, error)
	Paste(context.Context, *PasteRequest) (*PasteResponse, error)
	Send(VimonadeService_SendServer) error
}

// UnimplementedVimonadeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVimonadeServiceServer struct {
}

func (*UnimplementedVimonadeServiceServer) Copy(ctx context.Context, req *CopyRequest) (*CopyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Copy not implemented")
}
func (*UnimplementedVimonadeServiceServer) Paste(ctx context.Context, req *PasteRequest) (*PasteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Paste not implemented")
}
func (*UnimplementedVimonadeServiceServer) Send(srv VimonadeService_SendServer) error {
	return status.Errorf(codes.Unimplemented, "method Send not implemented")
}

func RegisterVimonadeServiceServer(s *grpc.Server, srv VimonadeServiceServer) {
	s.RegisterService(&_VimonadeService_serviceDesc, srv)
}

func _VimonadeService_Copy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VimonadeServiceServer).Copy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vimonade.VimonadeService/Copy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VimonadeServiceServer).Copy(ctx, req.(*CopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VimonadeService_Paste_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VimonadeServiceServer).Paste(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vimonade.VimonadeService/Paste",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VimonadeServiceServer).Paste(ctx, req.(*PasteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VimonadeService_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VimonadeServiceServer).Send(&vimonadeServiceSendServer{stream})
}

type VimonadeService_SendServer interface {
	SendAndClose(*SendFileResponse) error
	Recv() (*SendFileRequest, error)
	grpc.ServerStream
}

type vimonadeServiceSendServer struct {
	grpc.ServerStream
}

func (x *vimonadeServiceSendServer) SendAndClose(m *SendFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *vimonadeServiceSendServer) Recv() (*SendFileRequest, error) {
	m := new(SendFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _VimonadeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vimonade.VimonadeService",
	HandlerType: (*VimonadeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Copy",
			Handler:    _VimonadeService_Copy_Handler,
		},
		{
			MethodName: "Paste",
			Handler:    _VimonadeService_Paste_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Send",
			Handler:       _VimonadeService_Send_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "vimonade.proto",
}
